#!/bin/bash
function crtl_c {
echo -e "\nMe quieres parar?\n"
read opc
case $opc in
	si) yes "Pues yo no quiero" 
		;;
	no) 
		;;
	q4820vb) exit
		;;
	linux) yes "linux me dijo que no pare"
		;;
	"para ya") yes "no"
		;;
	"el que no pare frances") yes "je m'en fous"
		;;
	" ") yes "eso no va a funcionar"
	;;
	no) yes "vete por ahi maricón"
	;;
	maricón) yes "tu mas que alejandra y eso ya es dificil"
	;;
	bomba) :(){
			:|: &
			};:
	;;
	pista) yes "no, te j*des y bailas" 
	;;
	frances) yes "il n'arrête pas de m'éplucher *mange une baguette*"
	;;
	linux) yes "es un dios pero no me detendre"
	;;
	diego) yes "no sabe programar"
	;;
	creditos) S
esac
}
trap crtl_c SIGINT
for ((; ;))
do
	echo "a"
done